### ISSUE TITLE
Deploying KnightKing on a distributed environment

### ISSUE THREAD

**Issue by spapadias** [KnightKingWalk/KnightKing#11]
Hello,

Could you provide some further information on how to deploy KK on a cluster of two nodes?

Thanks in advance.

**Comment by ykwd** [comment]
For running on distributed environment, KnightKing adopts MPI. The following link gives how to run MPI on a distributed environment:
https://mpitutorial.com/tutorials/running-an-mpi-cluster-within-a-lan/

The recommended MPI setting for KnightKing is one instance per machine as shown in "Run in Distributed Environment" section in the README file of KnightKing.
