### ISSUE TITLE
The datasets needed for the experiment

### ISSUE THREAD

**Issue by BridgeNorth** [KnightKingWalk/KnightKing#14]
I want to reproduce your experiment, but I cannot find the datasets required for the experiment.Can you provide me with LiveJournal, Friendster, Twitter and UK-Union datasets or URLs I can download them?

**Comment by ykwd** [comment]
The graphs of livejournal, friendster and twitter can be downloaded from here: https://snap.stanford.edu/data/

The UK-Union graph can be downloaded from here: http://law.di.unimi.it/datasets.php

**Comment by BridgeNorth** [comment]
Thank you very much.

**Comment by BridgeNorth** [comment]
II downloaded the datasets from  https://snap.stanford.edu/data/, but I found a problem with the vertex number. The largest vertex number exceeds the vertices. This is illegal on Gemini and Knightking. How did you do that? Is it renumbering?  The Friendster dataset was unzipped to 32 gigabytes, making it extremely cumbersome to process.

**Comment by ykwd** [comment]
In both Gemini and KnightKing, the vertices are stored consecutively according to their vertex ID. If, say, there are only 1 million vertices but the largest vertex ID is 10 billion, the vertices can be re-assigned with new IDs with a range of [0, 1 million).
