### ISSUE TITLE
Assertion `local_e_num == local_edge_p' failed.

### ISSUE THREAD

**Issue by benbusath** [KnightKingWalk/KnightKing#15]
I am trying to run the node2vec app on a graph I made but I keep getting this error (assertion located in `graph.hpp`). The code does work on the karate.txt dataset, so I'm wondering if my graph structure is flawed in someway. Could someone explain to me what this assertion means and how I can go about avoiding this error?

**Comment by ykwd** [comment]
This assertion checks if the local_e_num (the edges that should belong to this server) equals local_edge_p (the edges that this server actually received). Could you provide an example of the format of your graph so I can reproduce this error?

**Comment by benbusath** [comment]
I was able to fix it, my issue was that my `-v` parameter for the number of vertices was lower than the actual total number of vertices in the input graph. I was running the code on a single machine, not a cluster. A nice improvement would be for the code to determine the number of vertices on the backend and not rely on human input, although I'm not sure how much this would hurt code efficiency.
