### ISSUE TITLE
关于代码的一点疑问

### ISSUE THREAD

**Issue by JingLiofLiJing** [KnightKingWalk/KnightKing#8]
如题，graph类中的 distributed_execute 函数额外开了一个线程用于接收消息，这里采用了异步收发的机制，但是在 recv_locks 释放逐 partition 的数据给主线程捕捉的时候，由于在wait之前释放了锁，可能存在主线程的处理函数在 wait 之前成功抢占到锁提前访问了未明确接收完数据的情况，我觉得可能会隐含造成数据破坏的可能，是不是应该把wait放在最后一个phase 的 for 循环中比较合理？

**Comment by ykwd** [comment]
我觉得你说的是对的，这应该是一个bug，谢谢

**Comment by spapadias** [comment]
Are you going to fix the bug? thanks

Is the code valid now?

**Comment by ykwd** [comment]
> Are you going to fix the bug? thanks
> 
> Is the code valid now?

Thanks for notice. I almost forgot this. I am gonna fix this soon in this week. And will let you know once this is done.

**Comment by ykwd** [comment]
Now it's fixed. Thanks for this issue.
